sonar.projectKey=galenos-pro-frontend
sonar.projectName=Galenos Pro Frontend
sonar.sources=src/app
sonar.exclusions=**/*.spec.ts,**/environments/**
sonar.javascript.lcov.reportPaths=coverage/frontend-galenos-pro/lcov.info
sonar.coverage.exclusions=**/app.config.ts,**/app.routes.ts,**/core/models/**
sonar.host.url=http://galenos-sonarqube:9000
