sonar.projectKey=galenos-frontend
sonar.projectName=Galenos Pro - Frontend Angular
sonar.projectVersion=0.0.0

sonar.sources=src/app
sonar.tests=src/app
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**,**/*.js

sonar.typescript.tsconfigPath=tsconfig.json

# Quality Gate
sonar.qualitygate.wait=true
