sonar.projectKey=galenos-pro-frontend
sonar.projectName=Galenos Pro Frontend
sonar.sources=src/app
sonar.exclusions=**/*.spec.ts,**/environments/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=http://galenos-sonarqube:9000
